### PR TITLE
feat(artifacts/bitbucket): Accept Bitbucket Server hooks

### PR DESCRIPTION
**Pull request by abergmeier**
Since Bitbuckets Server hooks are different from Bitbucket Cloud, now also
add support for the former, so can be triggered with on-prem.

### CODE REVIEW

**Comment by abergmeier** [comment]
Not tested yet.

**Comment by abergmeier** [comment]
Any guidance, how we could make this automatically testable would be appreciated.

**Comment by abergmeier** [comment]
Found 3 things still left to do:

- [ ] Support Bitbucket Server testing Request
  This is tricky, since Bitbucket Server seems to send a request without any content. It fails already in _Gate_.
- [ ] Fix bug for Merges
- [ ] Introduce tests

**Comment by abergmeier** [comment]
>  regarding your question on testing in #424 (comment), might be able to do something similar to the spec for handles initial github ping

Thanks for the pointers. Helped a lot. Since some problems come from interacting with _Gate_, is there a similar test in _Gate_?

**Comment by ethanfrogers** [comment]
spinnaker/spinnaker#3073.

We need to clean this area up a lot :/.

**Pull request merged**
