### PR TITLE
fix(provider/aws): AWS credentials at pubsub.amazon, issue #6061

### PR DESCRIPTION
**Pull request by atyutyunnik**
Credentials for AWS pubsub can now be specified like this:
```pubsub:
  enabled: true
  amazon:
    enabled: true
    accessKeyId: AXXXXXXXXXXXXXXXXX
    secretAccessKey: 9xxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Verified with my Spinnaker setup outside of AWS. I don't see how I can provide automated unit- and end-to-end testing without access credentials.

### CODE REVIEW

**Comment by atyutyunnik** [comment]
This is for https://github.com/spinnaker/spinnaker/issues/6061

**Review by robzienert — COMMENTED** [review]
Strongly recommend against using static AWS credentials - what purpose is this for?

**Comment by atyutyunnik** [comment]
> Strongly recommend against using static AWS credentials - what purpose is this for?

Our Spinnaker runs in a local cluster on prem, outside of AWS environment. What's the alternative? Use of static AWS credentials (accessKeyId/secretAccessKey) in Spinnaker is quite a norm, I could tell:
```deploymentConfigurations.providers.aws.accessKeyId/secretAccessKey
deploymentConfigurations.persistentStorage.s3.accessKeyId/secretAccessKey
deploymentConfigurations.ci.codebuild.accessKeyId/secretAccessKey
deploymentConfigurations.artifacts.s3.accounts.*.accessKeyId/secretAccessKey

```

**Comment by cfieber** [comment]
see https://github.com/spinnaker/spinnaker/issues/6061#issuecomment-713740678

If you are using something that is part of the Spinnaker project to deploy Spinnaker we would welcome a PR there that allows specifying AWS creds and helps in dropping them into the right spot in the deploy manifest

**Pull request closed without merging**
