### PR TITLE
fix(emailTemplate): Updates to swabbie notification template

### PR DESCRIPTION
**Pull request by aravindmd**
Updates to email template based on some feedback

- added region and account information 
- links to serverGroup now takes the user to the actual serverGroup instead of the search results
view
- option to link the slack channel in the email 
- cleanup to the email body

### CODE REVIEW

**Comment by aravindmd** [comment]
Screen Shot 2019-09-30 at 9 11 06 AM

**Comment by emjburns** [comment]
I feel like each server group takes up a large amount of space. Is there any way we could display them as something like `server group: account/region/name`? Or do you think that would be confusing?

**Comment by aravindmd** [comment]
> I feel like each server group takes up a large amount of space. Is there any way we could display them as something like `server group: account/region/name`? Or do you think that would be confusing?

That's true , @gcomstock can you provide some inputs here ?

**Comment by gcomstock** [comment]
Do we expect this list to be super long? If not, I don't think this current layout is an issue.

**Comment by emjburns** [comment]
I'm not sure how long we expect it to be. We can figure something out later if it ends up being a lot :)

**Comment by gcomstock** [comment]
Sounds good! Thank you

**Comment by aravindmd** [comment]
Sounds good , i'll merge this after i have the swabbie change merged.

**Comment by jeyrschabu** [comment]
Closing this guy as these changes were ported into https://github.com/spinnaker/echo/pull/671.

**Pull request closed without merging**
