### PR TITLE
Add slack template for manualJudgment.

### PR DESCRIPTION
**Pull request by duftler**
Add all templates for manualJudgmentContinue and manualJudgmentStop.
Enhance default body template for manualJudgment.

### CODE REVIEW

**Comment by duftler** [comment]
image

**Comment by duftler** [comment]
image

**Comment by duftler** [comment]
With a judgment input selected:

image

**Comment by duftler** [comment]
image

**Comment by duftler** [comment]
Some slack examples:

image

**Comment by duftler** [comment]
@tomaslin please review.

**Comment by ajordens** [comment]
LGTM

**Pull request merged**
