### PR TITLE
Add regex to docker image

### PR DESCRIPTION
**Pull request by bfarrell**
Add ability to handle regex in docker trigger.

### CODE REVIEW

**Comment by bfarrell** [comment]
@lwander : PTAL

**Comment by lwander** [comment]
Nice, LGTM. I'd like to see what @tomaslin thinks first, and then we can talk about surfacing this in Deck.

**Comment by tomaslin** [comment]
Please add some tests to ensure correct behavior of this feature. Otherwise looks good.

**Comment by bfarrell** [comment]
@tomaslin : Thanks, done

**Comment by lwander** [comment]
I'll merge once it's squashed

**Comment by bfarrell** [comment]
Squashed.  Let me know how you want to handle the UI.

**Comment by lwander** [comment]
Ran your UI changes locally, they work great

**Pull request merged**
