### PR TITLE
use bot notifications for Slack instead of incoming webhooks

### PR DESCRIPTION
**Pull request by anotherchrisberry**
The current Slack integration uses [incoming webhooks](https://api.slack.com/incoming-webhooks) to send messages to Slack rooms.

The problem with webhooks is that they are tied to the user who created the webhook, and cannot post to any private rooms unless the creator of the webhook has been explicitly invited into the room - not something most teams will want to do, as we are finding out at Netflix.

[Bots](https://api.slack.com/bot-users), however, are different. They can post messages into any public room and any private room _they've been invited into_, regardless of the permissions of the person who created the bot.

For whatever reason, the Slack API doesn't support JSON payloads for bots calling the [postMessage API](https://api.slack.com/methods/chat.postMessage), so we need to send the body as form data.

**This is a breaking change** for anyone currently integrated with Slack, as they'll need to create a bot and update the token in the [configuration](https://github.com/spinnaker/spinnaker/blob/master/config/echo.yml#L19). If this is going to cause grief, I can make this non-breaking with some work.

I will update the docs on spinnaker.io once we're ready to merge this.

@tomaslin @gregturn general feedback is appreciated. 

@spinnaker/reviewers feedback on backwards compatibility is appreciated. I don't know if anyone else has set up Slack integration - I don't recall complaints about the issue this PR is trying to solve, but it's possible people are only posting to public rooms, or they're already members of any private rooms that are set up to receive messages.

### CODE REVIEW

**Comment by gregturn** [comment]
Why not make bots another option instead of either or. I don't always want to stand up a bot.

**Comment by jtk54** [comment]
I think the benefits of creating a bot instead of a webhook outweigh the minimal config delta. The process seems almost identical. However, it seems like there are stricter limits on the number of bot integrations per team than web hooks -- Spinnaker team on slack has a max of 3... (I just tried to create one). Is this going to cause issues?

**Comment by anotherchrisberry** [comment]
@jtk54 Each bot user is treated as a separate integration, and free accounts (like the Spinnaker team) are limited to ten integrations. So it's potentially a concern, as the bot would eat into that limit. For paid teams, there's no limit.

@gregturn Standing up a bot isn't much different than setting up an incoming webhook, and the webhook limitations around sending messages to private channels is a problem - one you might not realize when setting up the initial configuration. Once your users start setting up notifications into private channels, you'll probably notice, and then you'll have to set up the bot, then reconfigure and redeploy Echo.

If we really want to support both, we can. But we'll need configuration and documentation about why you should choose one over the other, and we should make it very explicit.

Personally, I think the webhook approach is the wrong one. But that may be colored by the fact that I have to notify a bunch of users here at Netflix that those notifications they set up for private channels won't work until we get this bot configuration in place, and then I have to tell them to invite the bot into their channel. If we'd gone with a bot in the first place, we would have had a message in the UI telling them to invite the bot to the channel and all of this would have "just worked".

**Comment by jtk54** [comment]
SGTM.

**Comment by tomaslin** [comment]
I agree that if a web hook integration cannot talk to a private channel, it should be completely removed in favor of a bot integration.

**Comment by anotherchrisberry** [comment]
Just to be clear, I am not faulting anyone for going with the webhook approach originally. It's simpler, and the issue where it won't post to private channels wouldn't come up when spiking out the initial integration - if you create the webhook, it can post to any private channels you're a member of, so you wouldn't know about this limitation until some other user tried to post to a private channel you're not a member of. Not an easy thing to test - nor something I would have thought to test. And it's taken us five months to discover the issue!

**Comment by gregturn** [comment]
None taken. SGTM.

**Pull request merged**
