### PR TITLE
feat(triggers) Adds support for payloadConstraints on property files for build triggers

### PR DESCRIPTION
**Pull request by linjmeyer**
Implements [Spinnaker Issue #5053](https://github.com/spinnaker/spinnaker/issues/5053)

Use case is conditionally triggering pipelines after a successful Jenkins build.  For example, Jenkins may be setup for builds on all branches but Spinnaker pipelines should only be master.  More complex use cases are possible too, like triggering 'stage' pipelines on feature/* branches or when a Jenkins build has something like `deploy_target=stage`.

* Adds support for payloadConstrains: {} dictionary for Build triggers (e.g. Jenkins).  
* If payloadConstraints are present, then properties in the properties file must pass the constraints to trigger a build
* Regexp is supported (works the same as webhook and pub/sub payloadConstraints)
* Does not support Manual Pipeline triggers (ie: if build 30 fails constraints it can still be manually triggered after the fact)
* Only tested with Jenkins

I think it will work with other build systems as long as they support properties, but unfortunately I don't have any available to test.

### CODE REVIEW

**Comment by linjmeyer** [comment]
I should probably add: I'm not a Java dev and this is my first time contributing to Spinnaker outside the spin cli.  Feedback is very welcome

**Comment by linjmeyer** [comment]
@cfieber done!  Let me know what you think, and if you want me to fix the incorrect commit messages.

**Comment by cfieber** [comment]
Thanks for this!

**Comment by emjburns** [comment]
@linjmeyer Thanks for this, this is awesome!

**Pull request merged**
