### PR TITLE
fix(headers): Metadata requestHeaders lookup should be case insensitive

### PR DESCRIPTION
**Pull request by jonsie**
Same as https://github.com/spinnaker/echo/pull/863 but without the tests so as not to pull in the Kotlin dependency (which makes cherry picking the change complicated).

### CODE REVIEW

**Comment by psalaberria002** [comment]
Was this released in 1.19.6? We are still getting the same error.

**Comment by ezimanyi** [comment]
It was released in 1.19.6; I'd have to defer to @jonsie about why the error would still be happening with this fix.

**Comment by psalaberria002** [comment]
I built Echo locally on top of this patch and printed the headers from the TreeMap right before the check. `x-hub-signature` is in place, but the error still fires.
```
2020-04-28 20:25:27.036  WARN 1 --- [RxIoScheduler-2] c.n.s.e.p.eventhandlers.GitEventHandler  : [accept, accept-encoding, connection, content-length, content-type, host, user-agent, x-hub-signature, x-spinnaker-anonymous, x-spinnaker-request-id, x-spinnaker-user-origin]
2020-04-28 20:25:27.036  WARN 1 --- [RxIoScheduler-2] c.n.s.e.p.eventhandlers.GitEventHandler  : Received GitEvent from Github without secure signature for trigger configured with a secret
```

**Comment by jonsie** [comment]
I thought this error was accessing the property in the map.  Is GitHub expecting the header to be lower case? Is this a network error?

**Comment by psalaberria002** [comment]
Github is sending it as X-Hub-Signature. There is some logic in Echo converting those to lower case, and for some reason which I cannot figure out containsKey seems to be doing a case sensitive comparison. Do you know where the headers are set?

**Comment by psalaberria002** [comment]
I get a NullPointerException when calling `gitEvent.getDetails().getRequestHeaders().comparator().toString()` which suggests there is some other place in the code where the requestHeaders variable is initialized without the comparator.

**Comment by jonsie** [comment]
If you're spinning your wheels on it, I think a PR to just set `private static final String GITHUB_SECURE_SIGNATURE_HEADER = "x-hub-signature";` is fine.

**Pull request merged**
