### PR TITLE
fix(webhooks/stash): Adding jsonalias for refChanges field of StashWe…

### PR DESCRIPTION
**Pull request by ChrisTheShark**
…bhookEvent to account for Stash webhook payloads that follow this format.

This patch adds a simple json alias for the refChanges field of StashWebhookEvent to account for payloads that have a slightly different format of changes for the field name. Spinnaker issue 4427 reports this behavior as a NullPointerException on line 44 or 46 of StashWebhookEvent where refChanges is null. I experienced the NullPointerException originating at line 43. This shift in code location could be explained by changes in the file over time but I don't have the historical context. I built a custom echo image with this proposed fix to validate. This fix corrected Stash triggers in my case and has no impact to existing payloads that follow the refChanges format.

fix spinnaker/spinnaker#4427

### CODE REVIEW

**Comment by KellerII** [comment]
This is a much needed fix. As of now Spinnaker manifests deployments when leveraging Stash/Bitbucket are broken.

**Comment by Tamoghnasen9** [comment]
+1.

**Comment by danimorelo** [comment]
+1
This bug also prevents Managed Delivery to work when triggering from stash/bitbucket server

**Comment by mattgogerly** [comment]
@Mergifyio update

**Review by mattgogerly — APPROVED** [review]

**Pull request merged**
